import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import NavBar from "./../components/nav-bar/navBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
        {/* <NavBar/> */}
          {children}</Providers>
      </body>
    </html>
  )
}